### ISSUE TITLE
QoE computing

### ISSUE THREAD

**Issue by ForgetMe17** [InRaysee/vr-dash-tile-player#2]
It seems that we are using the bitrate that is to be downloaded in the formula, not the current playing bitrate.
we are using `getQualityFor()` to get the quality index.
https://github.com/InRaysee/vr-dash-tile-player/blob/ea798e02c1c12eda62ae2933302ba2cdf8da0690/aframe-based-tile-player/app/main.js#L526
but as the api doc says, [it gets the current download quality for media type video, audio or images](http://cdn.dashjs.org/latest/jsdoc/module-MediaPlayer.html#getQualityFor__anchor).

**Comment by ForgetMe17** [comment]
Sorry i have not noticed that there was a commit to update `playerQuality` to `playerDownloadingQualit`.

But i am now figuring out how to get the current playing bitrate, any help on this?

**Comment by InRaysee** [comment]
> Sorry i have not noticed that there was a commit to update `playerQuality` to `playerDownloadingQualit`.
> 
> But i am now figuring out how to get the current playing bitrate, any help on this?

Hi! Thanks for your contact.

Yeah we've noticed the function getQualityFor() is to get the current download quality instead of the current playing one, however we haven't fixed it because we still have other more important issues to do.

Here's a primary thought which you can check if it can help you. Since we've got the timeline and all the download requests as global variables, maybe you can find the chunks playing currently according to the timeline, then figure out the quality from the request list. It's a little complex and ineffective, anyway hope it can give you an idea to make use of these global variables to get what you need. ^^

BTW if any better idea please let me know. Thanks. XD

**Comment by ForgetMe17** [comment]
Hi @InRaysee ,

I think i have found a way to solve this issue using `QUALITY_CHANGE_RENDERED` in the MediaPlayerEvent.js
https://github.com/InRaysee/vr-dash-tile-player/blob/ea798e02c1c12eda62ae2933302ba2cdf8da0690/aframe-based-tile-player/dash.js/src/streaming/MediaPlayerEvents.js#L161-L165

Each time the rendered quality changed, it will raise `QUALITY_CHANGE_RENDERED` , so i add a listener on this event, and record  the new quality. 
```
    function quality_change_rendered_event(e){
        // console.log(e);
        $scope.playerRenderingQuality[e.info.count] = e.newQuality;
    }
```

This works fine witth me, maybe i can share with you if you like.

**Comment by InRaysee** [comment]
Thanks @ForgetMe17 ! 

That's a great way I think. Will consider this part in the future.
