### ISSUE TITLE
dashjs version

### ISSUE THREAD

**Issue by Vesper0704** [InRaysee/vr-dash-tile-player#7]
Hi,
I have tried to invoke ```player.updateSettings()``` to add customized property to the player(like you did in the project 'info'),but when I use ```player.getSettings()```, the property is not added successfully.
Would you mind telling me the version of dashjs you adapted and whether you modified the source code of dashjs? The dash.all.min.js you used seem to be v3.2.1. But I can not reproduce from the cdn.

Thank you!

**Comment by InRaysee** [comment]
> 

Hi,

Sorry for stopping the updates for such a long time.

I've updated the dash.js from v3.2.1 to v.4.3.0 and modfied some problems just now. However, dash.js v.3.2.1 is remained and still feasible.

If any customized property is necessary to be added into player's settings, you need to modify `Settings.js`, where with the property you want to add set to be `null`, then recompile your dash.js with the command `npm run build` according to the official README.md. Otherwise, the function cannot find the place to fill with your inputs.

More details for my modification on dash.js can be found in `changelog.txt` in my dash.js dictionary. Please let me know if still any possible.

BTW thanks for your continued attention XD.

**Comment by Vesper0704** [comment]
Thanks for the reply!
I have located the dash.all.debug.js and modify the ```function Settings()``` to add the customized property. And since I'm doing live streaming using rtmp, the synchronization problem just keeps coming out ( with mpd, I suppose), so I still stick with the lower version, where the live can be achieved without further .
It is great work you've done! Thanks for your sharing.

**Comment by InRaysee** [comment]
> Thanks for the reply! I have located the dash.all.debug.js and modify the `function Settings()` to add the customized property. And since I'm doing live streaming using rtmp, the synchronization problem just keeps coming out ( with mpd, I suppose), so I still stick with the lower version, where the live can be achieved without further . It is great work you've done! Thanks for your sharing.

We're doing live streaming too, but we find it always slow when we transcode
